[package]
name = "todo-actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version="1.0.228", features=["derive"]  }
serde_json = "1.0.145"
tokio = "1.47.1"
uuid = "1.18.1"
